/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description OAuth2 password flow: `username` is the user's e-mail.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reservations
         * @description Guests see their own reservations, staff those of their restaurant, admins all.
         */
        get: operations["list_reservations_api_v1_reservations_get"];
        put?: never;
        /** Create Reservation */
        post: operations["create_reservation_api_v1_reservations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/{reservation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reservation */
        get: operations["get_reservation_api_v1_reservations__reservation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Reservation
         * @description Reschedule, change party size or notes; staff may also move it to another table.
         */
        patch: operations["update_reservation_api_v1_reservations__reservation_id__patch"];
        trace?: never;
    };
    "/api/v1/reservations/{reservation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Reservation */
        post: operations["cancel_reservation_api_v1_reservations__reservation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/{reservation_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change Status
         * @description Staff lifecycle changes: confirm, seat, complete, no-show, cancel.
         */
        patch: operations["change_status_api_v1_reservations__reservation_id__status_patch"];
        trace?: never;
    };
    "/api/v1/restaurants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Restaurants */
        get: operations["list_restaurants_api_v1_restaurants_get"];
        put?: never;
        /** Create Restaurant */
        post: operations["create_restaurant_api_v1_restaurants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurants/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cities */
        get: operations["list_cities_api_v1_restaurants_cities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurants/{restaurant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Restaurant */
        get: operations["get_restaurant_api_v1_restaurants__restaurant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Restaurant */
        patch: operations["update_restaurant_api_v1_restaurants__restaurant_id__patch"];
        trace?: never;
    };
    "/api/v1/restaurants/{restaurant_id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Availability */
        get: operations["get_availability_api_v1_restaurants__restaurant_id__availability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurants/{restaurant_id}/availability/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Slots
         * @description Start times for a day (every 30 minutes) with how many tables are free for the party.
         */
        get: operations["get_slots_api_v1_restaurants__restaurant_id__availability_slots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restaurants/{restaurant_id}/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tables */
        get: operations["list_tables_api_v1_restaurants__restaurant_id__tables_get"];
        put?: never;
        /** Create Table */
        post: operations["create_table_api_v1_restaurants__restaurant_id__tables_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tables/{table_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Table
         * @description Soft delete: deactivates the table, keeping reservation history.
         */
        delete: operations["delete_table_api_v1_tables__table_id__delete"];
        options?: never;
        head?: never;
        /** Update Table */
        patch: operations["update_table_api_v1_tables__table_id__patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update User
         * @description Grant roles, assign staff to a restaurant, or (de)activate an account.
         */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AvailabilityRead */
        AvailabilityRead: {
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Party Size */
            party_size: number;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /** Tables */
            tables: components["schemas"]["TableRead"][];
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Page[ReservationRead] */
        Page_ReservationRead_: {
            /** Items */
            items: components["schemas"]["ReservationRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[RestaurantRead] */
        Page_RestaurantRead_: {
            /** Items */
            items: components["schemas"]["RestaurantRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ReservationCreate */
        ReservationCreate: {
            /** End At */
            end_at?: string | null;
            /** Guest Email */
            guest_email?: string | null;
            /** Guest Name */
            guest_name?: string | null;
            /** Guest Phone */
            guest_phone?: string | null;
            /** Notes */
            notes?: string | null;
            /** Party Size */
            party_size: number;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            /** Table Id */
            table_id: number;
        };
        /** ReservationRead */
        ReservationRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Guest Email */
            guest_email: string;
            /** Guest Name */
            guest_name: string;
            /** Guest Phone */
            guest_phone: string | null;
            /** Id */
            id: number;
            /** Notes */
            notes: string | null;
            /** Party Size */
            party_size: number;
            /** Restaurant Id */
            restaurant_id: number;
            /** Restaurant Name */
            restaurant_name: string;
            /** Restaurant Timezone */
            restaurant_timezone: string;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
            status: components["schemas"]["ReservationStatus"];
            /** Table Id */
            table_id: number;
            /** Table Label */
            table_label: string;
            /** User Id */
            user_id: number | null;
        };
        /**
         * ReservationStatus
         * @enum {string}
         */
        ReservationStatus: "pending" | "confirmed" | "seated" | "completed" | "cancelled" | "no_show";
        /** ReservationStatusUpdate */
        ReservationStatusUpdate: {
            status: components["schemas"]["ReservationStatus"];
        };
        /**
         * ReservationUpdate
         * @description Partial update. Omitting `end_at` while moving `start_at` keeps the duration.
         *
         *     `table_id` (moving to another table of the same restaurant) is for staff only.
         *     `notes` may be set to null to clear it; the other fields may not be null.
         */
        ReservationUpdate: {
            /** End At */
            end_at?: string | null;
            /** Notes */
            notes?: string | null;
            /** Party Size */
            party_size?: number | null;
            /** Start At */
            start_at?: string | null;
            /** Table Id */
            table_id?: number | null;
        };
        /** RestaurantCreate */
        RestaurantCreate: {
            /** City */
            city: string;
            /**
             * Closes At
             * Format: time
             */
            closes_at: string;
            /**
             * Default Duration Minutes
             * @default 90
             */
            default_duration_minutes: number;
            /** Name */
            name: string;
            /**
             * Opens At
             * Format: time
             */
            opens_at: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /** RestaurantRead */
        RestaurantRead: {
            /** City */
            city: string;
            /**
             * Closes At
             * Format: time
             */
            closes_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Default Duration Minutes */
            default_duration_minutes: number;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Opens At
             * Format: time
             */
            opens_at: string;
            /**
             * Table Count
             * @default 0
             */
            table_count: number;
            /** Timezone */
            timezone: string;
        };
        /**
         * RestaurantUpdate
         * @description Partial update: only the fields that are sent change; `null` is not a valid value.
         */
        RestaurantUpdate: {
            /** City */
            city?: string | null;
            /** Closes At */
            closes_at?: string | null;
            /** Default Duration Minutes */
            default_duration_minutes?: number | null;
            /** Name */
            name?: string | null;
            /** Opens At */
            opens_at?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** SlotRead */
        SlotRead: {
            /** Available */
            available: boolean;
            /**
             * End At
             * Format: date-time
             */
            end_at: string;
            /** Free Tables */
            free_tables: number;
            /** Local Time */
            local_time: string;
            /**
             * Start At
             * Format: date-time
             */
            start_at: string;
        };
        /** SlotsRead */
        SlotsRead: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Party Size */
            party_size: number;
            /** Slots */
            slots: components["schemas"]["SlotRead"][];
            /** Timezone */
            timezone: string;
        };
        /** TableCreate */
        TableCreate: {
            /** Capacity */
            capacity: number;
            /** Label */
            label: string;
        };
        /** TableRead */
        TableRead: {
            /** Capacity */
            capacity: number;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Label */
            label: string;
            /** Restaurant Id */
            restaurant_id: number;
        };
        /**
         * TableUpdate
         * @description Partial update: only the fields that are sent change; `null` is not a valid value.
         */
        TableUpdate: {
            /** Capacity */
            capacity?: number | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Label */
            label?: string | null;
        };
        /** TokenRead */
        TokenRead: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserRead */
        UserRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Restaurant Id */
            restaurant_id: number | null;
            role: components["schemas"]["UserRole"];
        };
        /** UserRegister */
        UserRegister: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /** Password */
            password: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "guest" | "staff" | "admin";
        /**
         * UserUpdate
         * @description Admin-only changes. `restaurant_id` may be explicitly null, hence `model_fields_set`.
         */
        UserUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Restaurant Id */
            restaurant_id?: number | null;
            role?: components["schemas"]["UserRole"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_reservations_api_v1_reservations_get: {
        parameters: {
            query?: {
                restaurant_id?: number | null;
                table_id?: number | null;
                status?: components["schemas"]["ReservationStatus"] | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReservationRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_reservation_api_v1_reservations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reservation_api_v1_reservations__reservation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_reservation_api_v1_reservations__reservation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_reservation_api_v1_reservations__reservation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_api_v1_reservations__reservation_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservationStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_restaurants_api_v1_restaurants_get: {
        parameters: {
            query?: {
                /** @description Exact city, case-insensitive */
                city?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RestaurantRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_restaurant_api_v1_restaurants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestaurantCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cities_api_v1_restaurants_cities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_restaurant_api_v1_restaurants__restaurant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_restaurant_api_v1_restaurants__restaurant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestaurantUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_availability_api_v1_restaurants__restaurant_id__availability_get: {
        parameters: {
            query: {
                start_at: string;
                end_at?: string | null;
                party_size: number;
            };
            header?: never;
            path: {
                restaurant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_slots_api_v1_restaurants__restaurant_id__availability_slots_get: {
        parameters: {
            query: {
                date: string;
                party_size: number;
            };
            header?: never;
            path: {
                restaurant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tables_api_v1_restaurants__restaurant_id__tables_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_table_api_v1_restaurants__restaurant_id__tables_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurant_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TableCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_table_api_v1_tables__table_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_table_api_v1_tables__table_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TableUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
